// scripts/seed.ts
import { MongoClient } from "mongodb"
import bcrypt from "bcryptjs"
import * as dotenv from "dotenv"
import { resolve } from "path"

dotenv.config({ path: resolve(process.cwd(), ".env.local") })
dotenv.config({ path: resolve(process.cwd(), ".env") })

const uri = process.env.DATABASE_URL!
if (!uri) { console.error("❌ DATABASE_URL topilmadi!"); process.exit(1) }

const templates = [
  { name: "Klassik Nikoh", slug: "klassik-nikoh", description: "Zamonaviy va nafis to'y taklifi. Oltin va oq ranglar.", category: "WEDDING", isPremium: false, price: 29900, sortOrder: 1, fields: { groom: { label: "Kuyov ismi", type: "text", required: true }, bride: { label: "Kelin ismi", type: "text", required: true }, date: { label: "To'y sanasi", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy nomi", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, message: { label: "Xabar", type: "textarea", required: false }, phone: { label: "Aloqa raqami", type: "tel", required: true } }, styles: { primaryColor: "#C9A84C", bgColor: "#FFF8F0", font: "Playfair Display", accent: "gold" } },
  { name: "Zamonaviy To'y", slug: "zamonaviy-toy", description: "Minimalist dizayn, qora va oltin ranglar.", category: "WEDDING", isPremium: true, price: 49900, sortOrder: 2, fields: { groom: { label: "Kuyov", type: "text", required: true }, bride: { label: "Kelin", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Restoran", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, dresscode: { label: "Kiyim kodi", type: "text", required: false }, phone: { label: "Aloqa", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#1A1A1A", bgColor: "#F5F5F0", font: "Cormorant", accent: "minimal" } },
  { name: "Bahor To'yi", slug: "bahor-toyi", description: "Gul va bahor motivli romantik to'y taklifi.", category: "WEDDING", isPremium: false, price: 34900, sortOrder: 3, fields: { groom: { label: "Kuyov", type: "text", required: true }, bride: { label: "Kelin", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#E8A4C8", bgColor: "#FFF0F5", font: "Dancing Script", accent: "floral" } },
  { name: "Tug'ilgan Kun - Klassik", slug: "tugilgan-kun-klassik", description: "Rang-barang va quvnoq tug'ilgan kun taklifi.", category: "BIRTHDAY", isPremium: false, price: 19900, sortOrder: 4, fields: { name: { label: "Ismi", type: "text", required: true }, age: { label: "Yosh", type: "number", required: false }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#FF6B6B", bgColor: "#FFF5F5", font: "Nunito", accent: "colorful" } },
  { name: "Bolalar Tug'ilgan Kuni", slug: "bolalar-tugilgan-kuni", description: "Bolalar uchun quvnoq va rang-barang taklif.", category: "BIRTHDAY", isPremium: false, price: 24900, sortOrder: 5, fields: { childName: { label: "Bola ismi", type: "text", required: true }, age: { label: "Nechanchi yoshi", type: "number", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, phone: { label: "Ota-ona raqami", type: "tel", required: true } }, styles: { primaryColor: "#4ECDC4", bgColor: "#F0FFFE", font: "Baloo 2", accent: "kids" } },
  { name: "Konsert Chipta", slug: "konsert-chipta", description: "Professional konsert va musiqa tadbirlari uchun chipta.", category: "CONCERT", isPremium: false, price: 39900, sortOrder: 6, fields: { artistName: { label: "Artist/Guruh nomi", type: "text", required: true }, eventName: { label: "Tadbir nomi", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Makon", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, ticketPrice: { label: "Chipta narxi", type: "text", required: false }, seatType: { label: "O'rindiq turi", type: "select", options: ["VIP", "Standard", "Fan Zone"], required: false }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#6C63FF", bgColor: "#0D0D1A", font: "Rajdhani", accent: "neon", dark: true } },
  { name: "Biznes Uchrashuv", slug: "biznes-uchrashuv", description: "Rasmiy biznes uchrashuvlar va korporativ tadbirlar uchun.", category: "MEETING", isPremium: false, price: 24900, sortOrder: 7, fields: { companyName: { label: "Kompaniya nomi", type: "text", required: true }, meetingTitle: { label: "Uchrashuv mavzusi", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, contactPerson: { label: "Aloqa shaxsi", type: "text", required: true }, phone: { label: "Telefon", type: "tel", required: true }, agenda: { label: "Kun tartibi", type: "textarea", required: false } }, styles: { primaryColor: "#2563EB", bgColor: "#F8FAFC", font: "Inter", accent: "corporate" } },
  { name: "Online Uchrashuv", slug: "online-uchrashuv", description: "Zoom/Meet/Teams kabi online uchrashuvlar uchun.", category: "MEETING", isPremium: false, price: 19900, sortOrder: 8, fields: { title: { label: "Uchrashuv nomi", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, platform: { label: "Platforma", type: "select", options: ["Zoom", "Google Meet", "Teams", "Telegram"], required: true }, meetingLink: { label: "Havola", type: "url", required: true }, organizer: { label: "Tashkilotchi", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#0EA5E9", bgColor: "#F0F9FF", font: "DM Sans", accent: "digital" } },
  { name: "Korporativ Tadbir", slug: "korporativ-tadbir", description: "Kompaniya bayramlari va korporativ tadbirlar uchun.", category: "CORPORATE", isPremium: true, price: 59900, sortOrder: 9, fields: { companyName: { label: "Kompaniya", type: "text", required: true }, eventName: { label: "Tadbir nomi", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Makon", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, dresscode: { label: "Dress code", type: "text", required: false }, phone: { label: "Telefon", type: "tel", required: true } }, styles: { primaryColor: "#1E3A5F", bgColor: "#F8F9FA", font: "Lato", accent: "professional" } },
  { name: "Konferensiya", slug: "konferensiya", description: "Ilmiy va professional konferensiyalar uchun.", category: "CONFERENCE", isPremium: false, price: 34900, sortOrder: 10, fields: { conferenceTitle: { label: "Konferensiya nomi", type: "text", required: true }, organizer: { label: "Tashkilotchi", type: "text", required: true }, startDate: { label: "Boshlanish sanasi", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Makon", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#7C3AED", bgColor: "#FAFAFA", font: "Source Sans Pro", accent: "academic" } },
  { name: "Bitirish Marosimi", slug: "bitirish-marosimi", description: "Maktab yoki universitet bitirish marosimi uchun.", category: "GRADUATION", isPremium: false, price: 29900, sortOrder: 11, fields: { graduateName: { label: "Bitiruvchi ismi", type: "text", required: true }, institution: { label: "Muassasa nomi", type: "text", required: true }, degree: { label: "Daraja/Sinf", type: "text", required: false }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#047857", bgColor: "#F0FDF4", font: "Merriweather", accent: "academic-warm" } },
  { name: "Yubileyi", slug: "yubileyi", description: "Muhim sanalar va yubileylar uchun maxsus taklif.", category: "ANNIVERSARY", isPremium: true, price: 44900, sortOrder: 12, fields: { name: { label: "Ism/Laqab", type: "text", required: true }, anniversary: { label: "Nechanchi yubileyi", type: "text", required: false }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#B45309", bgColor: "#FFFBEB", font: "Cinzel", accent: "luxury" } },
  { name: "Unashtiruv / Nikoh", slug: "unashtiruv-nikoh", description: "Unashtiruv va nikoh marosimlari uchun zamonaviy taklif.", category: "ENGAGEMENT", isPremium: false, price: 34900, sortOrder: 13, fields: { groom: { label: "Kuyov", type: "text", required: true }, bride: { label: "Kelin", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#DB2777", bgColor: "#FFF1F5", font: "Great Vibes", accent: "romantic" } },
  { name: "Chilla Marosimi", slug: "chilla-marosimi", description: "Yangi tug'ilgan chaqaloq uchun chilla marosimi taklifi.", category: "BABY_SHOWER", isPremium: false, price: 24900, sortOrder: 14, fields: { motherName: { label: "Ona ismi", type: "text", required: true }, babyName: { label: "Bola ismi", type: "text", required: false }, gender: { label: "Jinsi", type: "select", options: ["O'g'il", "Qiz", "Sir"], required: false }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#F9A8D4", bgColor: "#FFF0F7", font: "Quicksand", accent: "soft" } },
  { name: "Sport Tadbiri", slug: "sport-tadbiri", description: "Musobaqalar, turnirlar va sport tadbirlari uchun chipta.", category: "SPORTS", isPremium: false, price: 29900, sortOrder: 15, fields: { eventName: { label: "Tadbir nomi", type: "text", required: true }, sport: { label: "Sport turi", type: "text", required: true }, teams: { label: "Jamoalar", type: "text", required: false }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Stadium/Arena", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#DC2626", bgColor: "#FFF5F5", font: "Oswald", accent: "sports" } },
  { name: "Umumiy Chipta", slug: "umumiy-chipta", description: "Har qanday tadbir uchun universal chipta shabloni.", category: "TICKET", isPremium: false, price: 19900, sortOrder: 16, fields: { eventName: { label: "Tadbir nomi", type: "text", required: true }, organizer: { label: "Tashkilotchi", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, ticketType: { label: "Chipta turi", type: "text", required: false }, seatNumber: { label: "O'rin raqami", type: "text", required: false }, phone: { label: "Aloqa", type: "tel", required: true } }, styles: { primaryColor: "#374151", bgColor: "#F9FAFB", font: "IBM Plex Sans", accent: "ticket" } },
  { name: "Kompaniya Yubileyi", slug: "kompaniya-yubileyi", description: "Kompaniya tashkil etilgan yillik marosimi uchun.", category: "CORPORATE", isPremium: true, price: 69900, sortOrder: 17, fields: { companyName: { label: "Kompaniya nomi", type: "text", required: true }, years: { label: "Necha yil", type: "number", required: true }, date: { label: "Sana", type: "date", required: true }, time: { label: "Soat", type: "time", required: true }, venue: { label: "Makon", type: "text", required: true }, phone: { label: "Telefon", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#92400E", bgColor: "#FFFBEB", font: "Playfair Display", accent: "prestige" } },
  { name: "Ramazon Iftori", slug: "ramazon-iftori", description: "Ramazon oyi iftor ziyofati uchun maxsus taklif.", category: "OTHER", isPremium: false, price: 24900, sortOrder: 18, fields: { hostName: { label: "Mezbonlar", type: "text", required: true }, date: { label: "Sana", type: "date", required: true }, iftarTime: { label: "Iftor vaqti", type: "time", required: true }, venue: { label: "Joy", type: "text", required: true }, address: { label: "Manzil", type: "text", required: true }, phone: { label: "Aloqa", type: "tel", required: true }, message: { label: "Xabar", type: "textarea", required: false } }, styles: { primaryColor: "#065F46", bgColor: "#F0FDF4", font: "Amiri", accent: "islamic" } },
]

async function main() {
  const client = new MongoClient(uri)
  try {
    await client.connect()
    console.log("✅ MongoDB ga ulandi")
    const db = client.db("invitify")

    // Admin
    const adminEmail = process.env.ADMIN_EMAIL || "admin@invitify.uz"
    const adminPassword = process.env.ADMIN_PASSWORD || "Admin@123456"
    const existing = await db.collection("users").findOne({ email: adminEmail })
    if (!existing) {
      const hashed = await bcrypt.hash(adminPassword, 10)
      await db.collection("users").insertOne({ email: adminEmail, name: "Admin", password: hashed, role: "SUPER_ADMIN", createdAt: new Date(), updatedAt: new Date() })
      console.log(`✅ Admin yaratildi: ${adminEmail}`)
    } else {
      console.log(`ℹ️  Admin allaqachon mavjud: ${adminEmail}`)
    }

    // Templates
    let created = 0, updated = 0
    for (const tpl of templates) {
      const exists = await db.collection("templates").findOne({ slug: tpl.slug })
      if (!exists) {
        await db.collection("templates").insertOne({ ...tpl, isActive: true, createdAt: new Date(), updatedAt: new Date() })
        created++
      } else {
        await db.collection("templates").updateOne({ slug: tpl.slug }, { $set: { ...tpl, updatedAt: new Date() } })
        updated++
      }
    }
    console.log(`✅ Shablonlar: ${created} ta yangi, ${updated} ta yangilandi`)
    console.log(`\n🚀 Seed muvaffaqiyatli tugadi!`)
    console.log(`   Admin: ${adminEmail} / ${adminPassword}`)
    console.log(`   URL: http://localhost:3000`)
  } finally {
    await client.close()
  }
}

main().catch(e => { console.error("❌ Seed xatosi:", e); process.exit(1) })
